### ISSUE TITLE
Proxmox version?

### ISSUE THREAD

**Issue by emresaracoglu** [kidandcat/proxmox-rest-api-PHP#1]
Hello,

I can use for Proxmox version 5 ?

**Comment by kidandcat** [comment]
Hi,
This class is for interact with a simplificator layer done with a NodeJS server, this layer is private so I cannot show it to you, it manages users with its own database, and it interacts with Proxmox with this package:

[https://www.npmjs.com/package/proxmox-lib](https://www.npmjs.com/package/proxmox-lib)

You should check that NPM Package for a simple communication with Proxmox.


PD: Sorry but the php wrapper is on github just for learning purposes, it is useless with the simplificator layer. (you could ask [netelip](https://www.netelip.com/) for the simplificator layer code done in NodeJS)
